import json
import os
from typing import Optional
from urllib.parse import urlparse
from .base_scaffold import BaseScaffold
from .homeaffairs_gov_au import HomeAffairsScaffold
from .sso_agc_gov_sg import SSOAgcScaffold
from .pdpc_gov_sg import PDPCScaffold

class DynamicScaffold(BaseScaffold):
    """Dynamic scaffold populated from the scaffolds database or generated by the DOM Analyzer."""

    def __init__(self, domain: str, config: dict):
        self._domain = domain
        self._config = config

    @property
    def target_domain(self) -> str:
        return self._domain

    def get_transport_type(self) -> str:
        return self._config.get("transport_type", "auto")

    def get_custom_selectors(self) -> dict[str, str]:
        return {
            "content_area": self._config.get("content_area", "main, #content, article, body"),
            "pdf_links": self._config.get("pdf_links", 'a[href$=".pdf"]'),
            "article_links": self._config.get("article_links", "a"),
            "title": self._config.get("title", "h1"),
            "sections": self._config.get("sections", "h2, h3, p")
        }

    def get_keywords(self) -> list[str]:
        return self._config.get("keywords", ["law", "legislation", "regulation", "act"])


class ScaffoldRegistry:
    """OSI Layer 7 (Application): Registry to discover, match, and dynamically learn Scaffolds."""

    def __init__(self, scaffolds: list[BaseScaffold] | None = None):
        self._db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "scaffolds_db.json")
        self._configs = {}
        if os.path.exists(self._db_path):
            try:
                with open(self._db_path, "r", encoding="utf-8") as f:
                    self._configs = json.load(f)
            except Exception:
                pass

        self._scaffolds = {}
        # 1. Initialize static scaffolds
        if scaffolds is None:
            scaffolds = [
                HomeAffairsScaffold(),
                SSOAgcScaffold(),
                PDPCScaffold(),
            ]
        for s in scaffolds:
            self._scaffolds[s.target_domain] = s

        # 2. Add dynamic ones from DB if not already registered statically
        for domain, cfg in self._configs.items():
            if domain not in self._scaffolds:
                self._scaffolds[domain] = DynamicScaffold(domain, cfg)

    def get_scaffold_for_url(self, url: str) -> Optional[BaseScaffold]:
        """Match a URL to a registered scaffold based on domain."""
        domain = urlparse(url).netloc
        if not domain:
            return None
        # Support both 'www.example.com' and 'example.com' matching
        domain_lower = domain.lower()
        for target, scaffold in self._scaffolds.items():
            if target in domain_lower or domain_lower in target:
                return scaffold
        return None

    def learn_and_save(self, url: str, html_content: str, llm) -> Optional[dict[str, str]]:
        """Invokes LLM (DOMAnalyzer) to analyze HTML and generate/save CSS selectors for the domain."""
        domain = urlparse(url).netloc
        if not domain:
            return None

        # Clean subdomains like 'www.' for database keys
        domain_key = domain.lower()
        if domain_key.startswith("www."):
            domain_key = domain_key[4:]

        # Extract a structural HTML snippet (skeleton) to fit in context window
        from bs4 import BeautifulSoup
        soup = BeautifulSoup(html_content, "html.parser")
        
        # Remove noisy tags
        for tag in soup(["script", "style", "svg", "noscript", "iframe"]):
            tag.decompose()
            
        # Get head and body outline
        body = soup.find("body") or soup
        # Truncate text content of tags to keep structure clear
        for element in body.find_all(True):
            if element.string and len(element.string.strip()) > 100:
                element.string = element.string.strip()[:100] + "..."
        
        html_skeleton = str(body)[:8000]

        prompt = (
            f"You are the DOM Analyzer and Selector Generator for a legal crawling system.\n"
            f"Analyze the HTML skeleton below for the government website: '{url}' (domain: '{domain_key}').\n"
            f"Generate optimal CSS selectors to extract law articles and PDF files.\n\n"
            f"HTML SKELETON:\n{html_skeleton}"
        )

        schema = {
            "type": "object",
            "properties": {
                "content_area": {
                    "type": "string", 
                    "description": "CSS selector for the main article content container div, main tag, or article tag (e.g. '.content', 'main', '#article-body')"
                },
                "sections": {
                    "type": "string",
                    "description": "CSS selector for individual paragraphs or headings inside the content area (e.g. 'p, h2, h3', '.provision-item')"
                },
                "pdf_links": {
                    "type": "string",
                    "description": "CSS selector for identifying links to download PDF copies of the law (e.g. 'a[href$=\".pdf\"]', '.pdf-download a')"
                },
                "title": {
                    "type": "string",
                    "description": "CSS selector for the law or page title heading (e.g. 'h1', '.act-title')"
                },
                "keywords": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "5-10 keywords specific to this country/site context related to digital trade or data protection"
                }
            },
            "required": ["content_area", "sections", "pdf_links", "title", "keywords"]
        }

        try:
            print(f"\n[DOM Analyzer] Learning page structure for '{domain_key}' dynamically...")
            response = llm.complete(prompt, schema, agent_profile="dom_analyzer")
            
            # Save the new config
            self._configs[domain_key] = response
            with open(self._db_path, "w", encoding="utf-8") as f:
                json.dump(self._configs, f, indent=2, ensure_ascii=False)
                
            print(f"[DOM Analyzer] Success! Saved learned selectors for '{domain_key}' to scaffolds_db.json.")
            
            # Register the new DynamicScaffold
            scaffold = DynamicScaffold(domain_key, response)
            self._scaffolds[domain_key] = scaffold
            return scaffold.get_custom_selectors()
        except Exception as e:
            print(f"[DOM Analyzer] Failed to learn selectors: {e}")
            return None
