"""Supervised Fine-Tuning (SFT) script for Qwen using LoRA.

This script loads the distilled dataset generated by distill_qwen.py,
configures a LoRA target adapter for Qwen, and runs Hugging Face's SFTTrainer
to fine-tune the model locally.

Prerequisites:
    pip install torch transformers peft trl accelerate datasets

Run with:
    python tune_qwen.py --model_id Qwen/Qwen2.5-7B-Instruct --dataset qwen_distillation_dataset.jsonl
"""

from __future__ import annotations

import argparse
import os
import sys
import torch
from datasets import load_dataset
from peft import LoraConfig, get_peft_model
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    TrainingArguments,
)
from trl import SFTTrainer


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--model_id",
        default="Qwen/Qwen2.5-7B-Instruct",
        help="Base model ID from Hugging Face.",
    )
    parser.add_argument(
        "--dataset",
        default="qwen_distillation_dataset.jsonl",
        help="Path to the JSONL ChatML dataset.",
    )
    parser.add_argument(
        "--output_dir",
        default="./qwen-sft-lora",
        help="Where to save the fine-tuned LoRA adapters.",
    )
    args = parser.parse_args()

    print("=" * 60)
    print(" ZETARIX LOCAL QWEN FINE-TUNING PIPELINE (LoRA SFT)")
    print("=" * 60)
    print(f"Base Model:  {args.model_id}")
    print(f"Dataset:     {args.dataset}")
    print(f"Output Dir:  {args.output_dir}")
    print("-" * 60)

    if not os.path.exists(args.dataset):
        print(f"[ERROR] Dataset {args.dataset} not found. Please run distill_qwen.py first.")
        sys.exit(1)

    # 1. Load tokenizer and model
    print("Loading tokenizer and model...")
    tokenizer = AutoTokenizer.from_pretrained(args.model_id, trust_remote_code=True)
    tokenizer.pad_token = tokenizer.eos_token

    # Load in 4-bit/8-bit precision if GPU constraints exist, otherwise FP16/BF16
    device_map = "auto" if torch.cuda.is_available() else None
    torch_dtype = torch.bfloat16 if torch.cuda.is_available() and torch.cuda.is_bf16_supported() else torch.float16

    model = AutoModelForCausalLM.from_pretrained(
        args.model_id,
        device_map=device_map,
        torch_dtype=torch_dtype,
        trust_remote_code=True,
    )

    # 2. Configure LoRA
    print("Configuring LoRA adapters...")
    peft_config = LoraConfig(
        r=16,
        lora_alpha=32,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        lora_dropout=0.05,
        bias="none",
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(model, peft_config)
    model.print_trainable_parameters()

    # 3. Load dataset
    print("Loading dataset...")
    # Load dataset directly from JSONL
    dataset = load_dataset("json", data_files=args.dataset, split="train")

    def format_chatml(example):
        # Format dataset messages into ChatML string structure
        text = ""
        for msg in example["messages"]:
            text += f"<|im_start|>{msg['role']}\n{msg['content']}<|im_end|>\n"
        return {"text": text}

    formatted_dataset = dataset.map(format_chatml)

    # 4. Training Arguments
    training_args = TrainingArguments(
        output_dir=args.output_dir,
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        learning_rate=2e-4,
        logging_steps=10,
        num_train_epochs=3,
        save_strategy="epoch",
        fp16=not torch.cuda.is_bf16_supported() if torch.cuda.is_available() else False,
        bf16=torch.cuda.is_bf16_supported() if torch.cuda.is_available() else False,
        optim="adamw_torch",
        report_to="none",
    )

    # 5. Initialize SFTTrainer
    print("Initializing trainer...")
    trainer = SFTTrainer(
        model=model,
        train_dataset=formatted_dataset,
        dataset_text_field="text",
        max_seq_length=1024,
        tokenizer=tokenizer,
        args=training_args,
    )

    # 6. Run SFT training loop
    print("Starting SFT training...")
    trainer.train()

    print("\nTraining completed successfully!")
    trainer.model.save_pretrained(args.output_dir)
    tokenizer.save_pretrained(args.output_dir)
    print(f"Saved LoRA weights and tokenizer to: {os.path.abspath(args.output_dir)}")
    print("=" * 60)


if __name__ == "__main__":
    main()
